version: "3"
services:
  db:
    image: mariadb:11.2
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: concretizza
      MYSQL_ROOT_PASSWORD: 4321
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  db:
    driver: local