version: "3"
services:
  db:
    image: ankane/pgvector
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: musedoc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4321
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  db:
    driver: local